---
- set_fact:
    download_url: "{{ oc_macos_url }}"
    local_archive_path: "{{ oc_macos_archive }}"
  when: ansible_os_family == "Darwin"

- set_fact:
    download_url: "{{ oc_linux_url }}"
    local_archive_path: "{{ oc_linux_archive }}"
  when: (ansible_os_family == "RedHat") or (ansible_distribution == "Ubuntu")

- name: Retrieve oc archive
  get_url:
    url: "{{ download_url }}"
    dest: "{{ local_archive_path }}"
    force: yes

- name: Extract oc binary
  unarchive:
    src: "{{ local_archive_path }}"
    dest: "/tmp/"
    copy: "no"

- name: Use retrieved oc binary
  copy:
    remote_src: yes
    src: "{{ oc_binary_local_path }}"
    dest: "{{ oc_binary_install_path }}"
    mode: 0755
